### ISSUE TITLE
Crashes in Windows 10

### ISSUE THREAD

**Issue by mrkaban** [sambordeone/listsp#1]
Hello, you answered my mail via a private message on SourseForge.

This test build also does not run on Windows 10.

I no longer remember what exactly I wrote on SourseForge =))) but I remember that I noticed it after a website visitor wrote to me about it. And yes, I remembered, and let's, since we are talking about the site, I will show a link to the description of your program ([link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%83%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D1%8B/%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0/listsp-%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%B0%D0%BC%D0%B8,-%D1%81%D0%BB%D1%83%D0%B6%D0%B1%D0%B0%D0%BC%D0%B8,-%D0%B4%D1%80%D0%B0%D0%B9%D0%B2%D0%B5%D1%80%D0%B0%D0%BC%D0%B8.html)).

Now everyone is transferring the repositories to the github, I think it's time to move your program here!

**Comment by mrkaban** [comment]
When I try to start it, it does not load further.
![Снимок](https://user-images.githubusercontent.com/14289360/91868531-053c1400-ec9f-11ea-8ccf-f7cf6b3df109.png)

**Comment by sambordeone** [comment]
> 
> 
> When I try to start it, it does not load further.
> ![Снимок](https://user-images.githubusercontent.com/14289360/91868531-053c1400-ec9f-11ea-8ccf-f7cf6b3df109.png)

Thank You For Sharing.

Does this happen for every second or third or fourth run ?

Due to undocumented functions it crashes. I will change it soon.

Does it stop at this loading screen for each execution ?

How many times you have executed the program ?

Have you changed the settings 
Options Menu -> Process -> Use Old Methods For Process List
?

You can also change through command line.

There are two ways to start listsp:-
1) First is clicking on icon/exe
2) Using command line options ( listsp.exe /? )
    Using command line options ( listsp.exe -help )

**Please start listsp using following command line option :-**

**listsp.exe /p /oldmethod**

![2](https://user-images.githubusercontent.com/70567644/91875036-978ce980-ec98-11ea-8faa-d8a0580262cf.png)

**Comment by sambordeone** [comment]
If listsp starts by clicking the icon/exe then immediately change settings

Options Menu -> Process -> Use Old Methods For Process List

Screenshot :-

![1](https://user-images.githubusercontent.com/70567644/91875304-efc3eb80-ec98-11ea-8c2c-39eb9f841e46.png)

**Comment by sambordeone** [comment]
> 
> 
> Hello, you answered my mail via a private message on SourseForge.
> 
> This test build also does not run on Windows 10.
> 
> I no longer remember what exactly I wrote on SourseForge =))) but I remember that I noticed it after a website visitor wrote to me about it. And yes, I remembered, and let's, since we are talking about the site, I will show a link to the description of your program ([link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%83%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D1%8B/%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0/listsp-%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%B0%D0%BC%D0%B8,-%D1%81%D0%BB%D1%83%D0%B6%D0%B1%D0%B0%D0%BC%D0%B8,-%D0%B4%D1%80%D0%B0%D0%B9%D0%B2%D0%B5%D1%80%D0%B0%D0%BC%D0%B8.html)).
> 
> Now everyone is transferring the repositories to the github, I think it's time to move your program here!

On My PC Listsp is starting normally.

Please check command line options ( /? or -help ) to start it using various options

**Comment by mrkaban** [comment]
This problem appears every time. Further loading does not proceed, the program is closed and the main window does not appear.

I cannot change the settings, because the program does not open.

I can run it only through the command line - listsp.exe / p / oldmetnod.

After running through the command line, this setting was installed by itself and starts running through a double click.

**Comment by mrkaban** [comment]
However, I will not be able to explain to every new user that the program needs to be run for the first time through the command line with a parameter.

**Comment by sambordeone** [comment]
> 
> 
> This problem appears every time. Further loading does not proceed, the program is closed and the main window does not appear.
> 
> I cannot change the settings, because the program does not open.
> 
> I can run it only through the command line - listsp.exe / p / oldmetnod.
> 
> After running through the command line, this setting was installed by itself and starts running through a double click.

So Problem Solved ?

**Comment by mrkaban** [comment]
Yes

**Comment by sambordeone** [comment]
> 
> 
> Yes

I will fix it soon.

Thank you for helping.

Microsoft keeps on changing internal functions that's why this happens  ;(

That's why i kept this option.

All types of comments / Bugs / Suggestions / .... are welcomed
